# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Ssom' do
 pod 'GoogleMaps'
 pod 'Alamofire'
end

target 'SsomTests' do

end

target 'SsomUITests' do

end

