# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Ssom' do
 pod 'GoogleMaps'
 pod 'Alamofire'
 pod 'SDWebImage'

 pod 'Fabric'
 pod 'Crashlytics'

 pod 'KeychainAccess', '~> 2.4'

 pod 'Firebase'
 pod 'Firebase/Crash'
 pod 'Firebase/Auth'
 pod 'Firebase/Core'
 pod 'Firebase/Messaging'
 pod 'Firebase/RemoteConfig'

 pod 'Bolts'
 pod 'FBSDKCoreKit'
 pod 'FBSDKShareKit'
 pod 'FBSDKLoginKit' 

 pod 'Reveal-SDK', :configurations => ['Debug']

 pod 'OneSignal'
end

target 'SsomTests' do

end

target 'SsomUITests' do

end

