# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Ssom' do
 pod 'GoogleMaps'
 pod 'Alamofire'
 pod 'SDWebImage'
 pod 'UICountingLabel'

 pod 'Toast-Swift'

 pod 'Fabric'
 pod 'Crashlytics'

 pod 'KeychainAccess'

 pod 'Firebase'
 pod 'Firebase/Crash'
 pod 'Firebase/Auth'
 pod 'Firebase/Core'
 pod 'Firebase/Messaging'
 pod 'Firebase/RemoteConfig'

 pod 'Bolts'
 pod 'FBSDKCoreKit'
 pod 'FBSDKShareKit'
 pod 'FBSDKLoginKit' 

 pod 'Reveal-SDK', :configurations => ['Debug']

 pod 'OneSignal'

 pod 'BRYXBanner'

end

target 'SsomTests' do

end

target 'SsomUITests' do

end

swift_32 = ['Toast-Swift']
#swift4 = ['PalaverKit']

post_install do |installer|
  installer.pods_project.targets.each do |target|
    swift_version = nil

    if swift_32.include?(target.name)
      swift_version = '3.2'
    end

#    if swift4.include?(target.name)
#      swift_version = '4.0'
#    end

    if swift_version
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = swift_version
      end
    end
  end
end
